twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        moi: Victor Weiss
        PROJECT_NAME: Mon Super Site
        ADMIN_NAME: '%ADMIN_NAME%'
        MY_EMAIL: '%MY_EMAIL%'
        DOMAIN_NAME: '%DOMAIN_NAME%'
        SOCIALS:
            FB: https://facebook.com/maPageFb